apiVersion: apps/v1
kind: Deployment

# metadata
metadata:
  name: sceneclassifier-deployment
  labels:
    app: sceneclassifier
    type: front-end

# replicaset specs
spec:
  template: # pod template, same metadata and spec as pod.yaml
    metadata:
      name: sceneclassifier-pod
      labels:
          app: sceneclassifier
          type: front-end
    spec:
        containers:
          - name: sceneclassifier-container
            image: guolin1/sceneclassifier:1.0 # DockerHub
            ports:
              - containerPort: 8501
  replicas: 1 # number of pods to be deployed. 
              # Unfortunately when there are more than 1 pod running, cross-site request 
              # forgery (CSRF) protection may prevent user from uploading images for classification.
              # Hopefully this is something that will be fixed in future streamlit releases. 
              # To allow multi-replicas, set image to: guolin1/sceneclassifier:1.1 which has csrf protection disabled  
  selector:   # selector
    matchLabels:
      type: front-end