apiVersion: apps/v1
kind: ReplicaSet

# metadata
metadata:
  name: sceneclassifier-replicaset
  labels:
    app: sceneclassifier
    type: front-end

# replicaset specs
spec:
  template: # pod template
    metadata:
      name: sceneclassifier-pod
      labels:
          app: sceneclassifier
          type: front-end
    spec:
        containers:
          - name: sceneclassifier-container
            image: guolin1/sceneclassifier:1.0 # DockerHub
  replicas: 3 # number of pods
  selector:   # selector
    matchLabels:
      type: front-end