apiVersion: v1
kind: Service

metadata:
  name: sceneclassifier-service

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
  selector:
    app: sceneclassifier
    type: front-end